from .vector import PolyLine2D, Vector2D
from collections.abc import Sequence
from typing import Any, final

@final
class Layer:
    def __copy__(self, /) -> Layer: ...
    def __deepcopy__(self, /, _memo: Any) -> Layer: ...
    def __new__(cls, /, lines: Sequence[PolyLine2D] |None = None, texts: Sequence[Text] |None = None, style: LayerStyle |None = None) -> Layer: ...
    def __repr_svg_(self, /) -> str: ...
    def add_entity(self, /, entity: Any) -> None: ...
    def add_line(self, /, line: PolyLine2D) -> None: ...
    def add_text(self, /, text: Text) -> None: ...
    def bbox(self, /) -> tuple[float, float, float, float] |None: ...
    def copy(self, /) -> Layer: ...
    @property
    def lines(self, /) -> list[PolyLine2D]: ...
    @lines.setter
    def lines(self, /, value: Sequence[PolyLine2D]) -> None: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> Layer: ...
    def rotate(self, /, angle: float, radians: bool, center: Vector2D |Sequence[float] |None) -> Layer: ...
    def scale(self, /, factor: float) -> Layer: ...
    @property
    def style(self, /) -> LayerStyle: ...
    @style.setter
    def style(self, /, value: LayerStyle) -> None: ...
    @property
    def texts(self, /) -> list[Text]: ...
    @texts.setter
    def texts(self, /, value: Sequence[Text]) -> None: ...

@final
class LayerEditor:
    def __enter__(self, /) -> LayerEditor: ...
    def __exit__(self, /, _exc_type: Any |None, _exc: Any |None, _tb: Any |None) -> bool: ...
    def add(self, /, entity: Any) -> None: ...
    def add_line(self, /, line: PolyLine2D) -> None: ...
    def add_text(self, /, text: Text) -> None: ...
    @property
    def style(self, /) -> LayerStyleEditor: ...
    @style.setter
    def style(self, /, style: LayerStyle) -> None: ...

@final
class LayerStyle:
    def __copy__(self, /) -> LayerStyle: ...
    def __deepcopy__(self, /, _memo: Any) -> LayerStyle: ...
    def __new__(cls, /, stroke: str |None = None, stroke_width: float = 0.25, fill: str |None = None, font_size: float |None = None, font_family: str |None = None, visible: bool = True) -> LayerStyle: ...
    def copy(self, /) -> LayerStyle: ...
    @property
    def fill(self, /) -> str |None: ...
    @fill.setter
    def fill(self, /, value: str |None) -> None: ...
    @property
    def font_family(self, /) -> str |None: ...
    @font_family.setter
    def font_family(self, /, value: str |None) -> None: ...
    @property
    def font_size(self, /) -> float |None: ...
    @font_size.setter
    def font_size(self, /, value: float |None) -> None: ...
    def scaled(self, /, factor: float) -> LayerStyle: ...
    @property
    def stroke(self, /) -> str |None: ...
    @stroke.setter
    def stroke(self, /, value: str |None) -> None: ...
    @property
    def stroke_width(self, /) -> float: ...
    @stroke_width.setter
    def stroke_width(self, /, value: float) -> None: ...
    @property
    def visible(self, /) -> bool: ...
    @visible.setter
    def visible(self, /, value: bool) -> None: ...

@final
class LayerStyleEditor:
    @property
    def fill(self, /) -> str |None: ...
    @fill.setter
    def fill(self, /, fill: str |None) -> None: ...
    @property
    def font_family(self, /) -> str |None: ...
    @font_family.setter
    def font_family(self, /, font_family: str |None) -> None: ...
    @property
    def font_size(self, /) -> float |None: ...
    @font_size.setter
    def font_size(self, /, font_size: float |None) -> None: ...
    @property
    def stroke(self, /) -> str |None: ...
    @stroke.setter
    def stroke(self, /, stroke: str |None) -> None: ...
    @property
    def stroke_width(self, /) -> float: ...
    @stroke_width.setter
    def stroke_width(self, /, stroke_width: float) -> None: ...
    @property
    def visible(self, /) -> bool: ...
    @visible.setter
    def visible(self, /, visible: bool) -> None: ...

@final
class Layout:
    def __copy__(self, /) -> Layout: ...
    def __deepcopy__(self, /, _memo: Any) -> Layout: ...
    def __new__(cls, /, parts: Sequence[Part] |None = None) -> Layout: ...
    def __repr_svg_(self, /) -> str: ...
    def add_part(self, /, part: Part) -> None: ...
    def append_left(self, /, other: Layout, distance: float = 0.0) -> Layout: ...
    def append_top(self, /, other: Layout, distance: float = 0.0) -> Layout: ...
    def bbox(self, /) -> tuple[float, float, float, float] |None: ...
    def copy(self, /) -> Layout: ...
    def export_dxf(self, /, path: str) -> None: ...
    def export_svg(self, /, path: str, border: float = 0.0) -> None: ...
    @property
    def height(self, /) -> float: ...
    def join(self, /, other: Layout) -> Layout: ...
    @property
    def max_x(self, /) -> float: ...
    @property
    def max_y(self, /) -> float: ...
    @property
    def min_x(self, /) -> float: ...
    @property
    def min_y(self, /) -> float: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> Layout: ...
    def move_to(self, /, target: Vector2D |Sequence[float]) -> None: ...
    @property
    def parts(self, /) -> list[Part]: ...
    @parts.setter
    def parts(self, /, value: Sequence[Part]) -> None: ...
    def rotate(self, /, angle: float, radians: bool, center: Vector2D |Sequence[float] |None) -> Layout: ...
    def scale(self, /, factor: float) -> Layout: ...
    @staticmethod
    def stack_column(parts: Sequence[Any], distance: float, center_x: bool = True) -> Layout: ...
    @staticmethod
    def stack_row(parts: Sequence[Any], distance: float, center_y: bool = True) -> Layout: ...
    def to_svg_string(self, /, border: float = 0.0) -> str: ...
    @property
    def width(self, /) -> float: ...

@final
class Part:
    def __copy__(self, /) -> Part: ...
    def __deepcopy__(self, /, _memo: Any) -> Part: ...
    def __new__(cls, /, layers: dict[str, Layer] |None = None, name: str |None = None, material_code: str = ...) -> Part: ...
    def __repr_svg_(self, /) -> str: ...
    def add_entity(self, /, layer_name: str, entity: Any) -> None: ...
    def add_line(self, /, layer_name: str, line: PolyLine2D) -> None: ...
    def add_text(self, /, layer_name: str, text: Text) -> None: ...
    def bbox(self, /) -> tuple[float, float, float, float] |None: ...
    def copy(self, /) -> Part: ...
    def layer(self, /, layer_name: str, style: LayerStyle |None = None) -> LayerEditor: ...
    @property
    def layers(self, /) -> dict[str, Layer]: ...
    @layers.setter
    def layers(self, /, value: dict[str, Layer]) -> None: ...
    @property
    def material_code(self, /) -> str: ...
    @material_code.setter
    def material_code(self, /, value: str) -> None: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> Part: ...
    @property
    def name(self, /) -> str |None: ...
    @name.setter
    def name(self, /, value: str |None) -> None: ...
    def rotate(self, /, angle: float, radians: bool, center: Vector2D |Sequence[float] |None) -> Part: ...
    def scale(self, /, factor: float) -> Part: ...

@final
class Text:
    def __copy__(self, /) -> Text: ...
    def __deepcopy__(self, /, _memo: Any) -> Text: ...
    def __new__(cls, /, text: str, p1: Vector2D |Sequence[float], p2: Vector2D |Sequence[float], size: float |None = None, height: float = 0.8, space: float = 0.2, align: float = ..., valign: float = 0.5) -> Text: ...
    @property
    def align(self, /) -> float: ...
    @align.setter
    def align(self, /, value: float) -> None: ...
    def bbox(self, /) -> tuple[float, float, float, float] |None: ...
    def copy(self, /) -> Text: ...
    def get_anchor(self, /) -> str: ...
    @property
    def height(self, /) -> float: ...
    @height.setter
    def height(self, /, value: float) -> None: ...
    def move(self, /, offset: Vector2D |Sequence[float]) -> Text: ...
    @property
    def p1(self, /) -> Vector2D: ...
    @p1.setter
    def p1(self, /, value: Vector2D) -> None: ...
    @property
    def p2(self, /) -> Vector2D: ...
    @p2.setter
    def p2(self, /, value: Vector2D) -> None: ...
    def rotate(self, /, angle: float, radians: bool, center: Vector2D |Sequence[float] |None) -> Text: ...
    def scale(self, /, factor: float) -> Text: ...
    def set_alignment(self, /, align: float, valign: float |None = None) -> None: ...
    @property
    def size(self, /) -> float |None: ...
    @size.setter
    def size(self, /, value: float |None) -> None: ...
    @property
    def space(self, /) -> float: ...
    @space.setter
    def space(self, /, value: float) -> None: ...
    @property
    def text(self, /) -> str: ...
    @text.setter
    def text(self, /, value: str) -> None: ...
    @property
    def valign(self, /) -> float: ...
    @valign.setter
    def valign(self, /, value: float) -> None: ...
